# Generated by Django 4.0 on 2021-12-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilova', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='definition',
            new_name='definition1',
        ),
        migrations.AddField(
            model_name='service',
            name='definition2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='definition3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='definition4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='definition5',
            field=models.TextField(blank=True),
        ),
    ]
