# Generated by Django 4.0 on 2021-12-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilova', '0002_rename_definition_service_definition1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
